project_id = "txbfdrriwaynfeurqkea"

[functions.manage-users]
verify_jwt = false

[functions.create-board-users]
verify_jwt = false

[functions.member-signup]
verify_jwt = false

[functions.send-push]
verify_jwt = false

[functions.notify-edit-request]
verify_jwt = false

[functions.extern-signup]
verify_jwt = false

[functions.process-email-queue]
verify_jwt = true

[functions.reset-mfa]
verify_jwt = false

[functions.send-transactional-email]
verify_jwt = true

[functions.preview-transactional-email]
verify_jwt = false

[functions.handle-email-unsubscribe]
verify_jwt = false

[functions.handle-email-suppression]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.payments-webhook]
verify_jwt = false

[functions.notify-membership-request]
verify_jwt = false

[functions.sync-outlook-contacts]
verify_jwt = false

[functions.informer-sync]
verify_jwt = false

[functions.sync-topical-calendar]
verify_jwt = false

[functions.sync-coffeeshopregister]
verify_jwt = false
