/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/_dashboard'
import { Route as ExternLoginRouteImport } from './routes/extern-login'
import { Route as KoppelenRouteImport } from './routes/koppelen'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MfaSetupRouteImport } from './routes/mfa-setup'
import { Route as MfaVerifyRouteImport } from './routes/mfa-verify'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as UnsubscribeRouteImport } from './routes/unsubscribe'
import { Route as DashboardIndexRouteImport } from './routes/_dashboard/index'
import { Route as DashboardAccountsRouteImport } from './routes/_dashboard/accounts'
import { Route as DashboardBestuurBeheerRouteImport } from './routes/_dashboard/bestuur-beheer'
import { Route as DashboardCommunityRouteImport } from './routes/_dashboard/community'
import { Route as DashboardEmailTemplatesRouteImport } from './routes/_dashboard/email-templates'
import { Route as DashboardFinancienRouteImport } from './routes/_dashboard/financien'
import { Route as DashboardGoedkeuringenRouteImport } from './routes/_dashboard/goedkeuringen'
import { Route as DashboardJaarplanRouteImport } from './routes/_dashboard/jaarplan'
import { Route as DashboardKerngegevensRouteImport } from './routes/_dashboard/kerngegevens'
import { Route as DashboardLedenBetalingenRouteImport } from './routes/_dashboard/leden-betalingen'
import { Route as DashboardMijnAccountRouteImport } from './routes/_dashboard/mijn-account'
import { Route as AShareCodeRouteImport } from './routes/a.$shareCode'
import { Route as CheckoutReturnRouteImport } from './routes/checkout/return'
import { Route as EnqueteExternIdRouteImport } from './routes/enquete-extern.$id'
import { Route as ExternIndexRouteImport } from './routes/extern/index'
import { Route as ExternProfielRouteImport } from './routes/extern/profiel'
import { Route as DashboardAgendaIndexRouteImport } from './routes/_dashboard/agenda.index'
import { Route as DashboardAgendaEventIdRouteImport } from './routes/_dashboard/agenda.$eventId'
import { Route as DashboardCoffeeshopregisterIndexRouteImport } from './routes/_dashboard/coffeeshopregister.index'
import { Route as DashboardEnquetesIndexRouteImport } from './routes/_dashboard/enquetes.index'
import { Route as DashboardExternePartijenIndexRouteImport } from './routes/_dashboard/externe-partijen.index'
import { Route as DashboardExternePartijenIdRouteImport } from './routes/_dashboard/externe-partijen.$id'
import { Route as DashboardLedenIndexRouteImport } from './routes/_dashboard/leden.index'
import { Route as DashboardLedenIdRouteImport } from './routes/_dashboard/leden.$id'
import { Route as DashboardLedenvoordelenIndexRouteImport } from './routes/_dashboard/ledenvoordelen.index'
import { Route as DashboardLedenvoordelenIdRouteImport } from './routes/_dashboard/ledenvoordelen.$id'
import { Route as DashboardLocatiesIndexRouteImport } from './routes/_dashboard/locaties.index'
import { Route as DashboardLocatiesGemeenteRouteImport } from './routes/_dashboard/locaties.$gemeente'
import { Route as EnquetesIdReviewRouteImport } from './routes/enquetes.$id.review'
import { Route as ExternGemeenteGemeenteRouteImport } from './routes/extern/gemeente.$gemeente'
import { Route as ExternProductIdRouteImport } from './routes/extern/product.$id'
import { Route as DashboardCoffeeshopregisterGemeenteGemeenteRouteImport } from './routes/_dashboard/coffeeshopregister.gemeente.$gemeente'
import { Route as DashboardEnquetesIdIndexRouteImport } from './routes/_dashboard/enquetes.$id.index'
import { Route as DashboardEnquetesIdBeheerRouteImport } from './routes/_dashboard/enquetes.$id.beheer'
import { Route as ApiPublicAgendaImageCodeRouteImport } from './routes/api/public/agenda-image.$code'

const DashboardRoute = DashboardRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ExternLoginRoute = ExternLoginRouteImport.update({
  id: '/extern-login',
  path: '/extern-login',
  getParentRoute: () => rootRouteImport,
} as any)
const KoppelenRoute = KoppelenRouteImport.update({
  id: '/koppelen',
  path: '/koppelen',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MfaSetupRoute = MfaSetupRouteImport.update({
  id: '/mfa-setup',
  path: '/mfa-setup',
  getParentRoute: () => rootRouteImport,
} as any)
const MfaVerifyRoute = MfaVerifyRouteImport.update({
  id: '/mfa-verify',
  path: '/mfa-verify',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const UnsubscribeRoute = UnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAccountsRoute = DashboardAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBestuurBeheerRoute = DashboardBestuurBeheerRouteImport.update({
  id: '/bestuur-beheer',
  path: '/bestuur-beheer',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCommunityRoute = DashboardCommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardEmailTemplatesRoute = DashboardEmailTemplatesRouteImport.update({
  id: '/email-templates',
  path: '/email-templates',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardFinancienRoute = DashboardFinancienRouteImport.update({
  id: '/financien',
  path: '/financien',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardGoedkeuringenRoute = DashboardGoedkeuringenRouteImport.update({
  id: '/goedkeuringen',
  path: '/goedkeuringen',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardJaarplanRoute = DashboardJaarplanRouteImport.update({
  id: '/jaarplan',
  path: '/jaarplan',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardKerngegevensRoute = DashboardKerngegevensRouteImport.update({
  id: '/kerngegevens',
  path: '/kerngegevens',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardLedenBetalingenRoute =
  DashboardLedenBetalingenRouteImport.update({
    id: '/leden-betalingen',
    path: '/leden-betalingen',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardMijnAccountRoute = DashboardMijnAccountRouteImport.update({
  id: '/mijn-account',
  path: '/mijn-account',
  getParentRoute: () => DashboardRoute,
} as any)
const AShareCodeRoute = AShareCodeRouteImport.update({
  id: '/a/$shareCode',
  path: '/a/$shareCode',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutReturnRoute = CheckoutReturnRouteImport.update({
  id: '/checkout/return',
  path: '/checkout/return',
  getParentRoute: () => rootRouteImport,
} as any)
const EnqueteExternIdRoute = EnqueteExternIdRouteImport.update({
  id: '/enquete-extern/$id',
  path: '/enquete-extern/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ExternIndexRoute = ExternIndexRouteImport.update({
  id: '/extern/',
  path: '/extern/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExternProfielRoute = ExternProfielRouteImport.update({
  id: '/extern/profiel',
  path: '/extern/profiel',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAgendaIndexRoute = DashboardAgendaIndexRouteImport.update({
  id: '/agenda/',
  path: '/agenda/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAgendaEventIdRoute = DashboardAgendaEventIdRouteImport.update({
  id: '/agenda/$eventId',
  path: '/agenda/$eventId',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCoffeeshopregisterIndexRoute =
  DashboardCoffeeshopregisterIndexRouteImport.update({
    id: '/coffeeshopregister/',
    path: '/coffeeshopregister/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardEnquetesIndexRoute = DashboardEnquetesIndexRouteImport.update({
  id: '/enquetes/',
  path: '/enquetes/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardExternePartijenIndexRoute =
  DashboardExternePartijenIndexRouteImport.update({
    id: '/externe-partijen/',
    path: '/externe-partijen/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardExternePartijenIdRoute =
  DashboardExternePartijenIdRouteImport.update({
    id: '/externe-partijen/$id',
    path: '/externe-partijen/$id',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardLedenIndexRoute = DashboardLedenIndexRouteImport.update({
  id: '/leden/',
  path: '/leden/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardLedenIdRoute = DashboardLedenIdRouteImport.update({
  id: '/leden/$id',
  path: '/leden/$id',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardLedenvoordelenIndexRoute =
  DashboardLedenvoordelenIndexRouteImport.update({
    id: '/ledenvoordelen/',
    path: '/ledenvoordelen/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardLedenvoordelenIdRoute =
  DashboardLedenvoordelenIdRouteImport.update({
    id: '/ledenvoordelen/$id',
    path: '/ledenvoordelen/$id',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardLocatiesIndexRoute = DashboardLocatiesIndexRouteImport.update({
  id: '/locaties/',
  path: '/locaties/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardLocatiesGemeenteRoute =
  DashboardLocatiesGemeenteRouteImport.update({
    id: '/locaties/$gemeente',
    path: '/locaties/$gemeente',
    getParentRoute: () => DashboardRoute,
  } as any)
const EnquetesIdReviewRoute = EnquetesIdReviewRouteImport.update({
  id: '/enquetes/$id/review',
  path: '/enquetes/$id/review',
  getParentRoute: () => rootRouteImport,
} as any)
const ExternGemeenteGemeenteRoute = ExternGemeenteGemeenteRouteImport.update({
  id: '/extern/gemeente/$gemeente',
  path: '/extern/gemeente/$gemeente',
  getParentRoute: () => rootRouteImport,
} as any)
const ExternProductIdRoute = ExternProductIdRouteImport.update({
  id: '/extern/product/$id',
  path: '/extern/product/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardCoffeeshopregisterGemeenteGemeenteRoute =
  DashboardCoffeeshopregisterGemeenteGemeenteRouteImport.update({
    id: '/coffeeshopregister/gemeente/$gemeente',
    path: '/coffeeshopregister/gemeente/$gemeente',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardEnquetesIdIndexRoute =
  DashboardEnquetesIdIndexRouteImport.update({
    id: '/enquetes/$id/',
    path: '/enquetes/$id/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardEnquetesIdBeheerRoute =
  DashboardEnquetesIdBeheerRouteImport.update({
    id: '/enquetes/$id/beheer',
    path: '/enquetes/$id/beheer',
    getParentRoute: () => DashboardRoute,
  } as any)
const ApiPublicAgendaImageCodeRoute =
  ApiPublicAgendaImageCodeRouteImport.update({
    id: '/api/public/agenda-image/$code',
    path: '/api/public/agenda-image/$code',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof DashboardIndexRoute
  '/extern-login': typeof ExternLoginRoute
  '/koppelen': typeof KoppelenRoute
  '/login': typeof LoginRoute
  '/mfa-setup': typeof MfaSetupRoute
  '/mfa-verify': typeof MfaVerifyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/accounts': typeof DashboardAccountsRoute
  '/bestuur-beheer': typeof DashboardBestuurBeheerRoute
  '/community': typeof DashboardCommunityRoute
  '/email-templates': typeof DashboardEmailTemplatesRoute
  '/financien': typeof DashboardFinancienRoute
  '/goedkeuringen': typeof DashboardGoedkeuringenRoute
  '/jaarplan': typeof DashboardJaarplanRoute
  '/kerngegevens': typeof DashboardKerngegevensRoute
  '/leden-betalingen': typeof DashboardLedenBetalingenRoute
  '/mijn-account': typeof DashboardMijnAccountRoute
  '/a/$shareCode': typeof AShareCodeRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/enquete-extern/$id': typeof EnqueteExternIdRoute
  '/extern/profiel': typeof ExternProfielRoute
  '/extern/': typeof ExternIndexRoute
  '/agenda/$eventId': typeof DashboardAgendaEventIdRoute
  '/externe-partijen/$id': typeof DashboardExternePartijenIdRoute
  '/leden/$id': typeof DashboardLedenIdRoute
  '/ledenvoordelen/$id': typeof DashboardLedenvoordelenIdRoute
  '/locaties/$gemeente': typeof DashboardLocatiesGemeenteRoute
  '/enquetes/$id/review': typeof EnquetesIdReviewRoute
  '/extern/gemeente/$gemeente': typeof ExternGemeenteGemeenteRoute
  '/extern/product/$id': typeof ExternProductIdRoute
  '/agenda/': typeof DashboardAgendaIndexRoute
  '/coffeeshopregister/': typeof DashboardCoffeeshopregisterIndexRoute
  '/enquetes/': typeof DashboardEnquetesIndexRoute
  '/externe-partijen/': typeof DashboardExternePartijenIndexRoute
  '/leden/': typeof DashboardLedenIndexRoute
  '/ledenvoordelen/': typeof DashboardLedenvoordelenIndexRoute
  '/locaties/': typeof DashboardLocatiesIndexRoute
  '/coffeeshopregister/gemeente/$gemeente': typeof DashboardCoffeeshopregisterGemeenteGemeenteRoute
  '/enquetes/$id/beheer': typeof DashboardEnquetesIdBeheerRoute
  '/api/public/agenda-image/$code': typeof ApiPublicAgendaImageCodeRoute
  '/enquetes/$id/': typeof DashboardEnquetesIdIndexRoute
}
export interface FileRoutesByTo {
  '/extern-login': typeof ExternLoginRoute
  '/koppelen': typeof KoppelenRoute
  '/login': typeof LoginRoute
  '/mfa-setup': typeof MfaSetupRoute
  '/mfa-verify': typeof MfaVerifyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/accounts': typeof DashboardAccountsRoute
  '/bestuur-beheer': typeof DashboardBestuurBeheerRoute
  '/community': typeof DashboardCommunityRoute
  '/email-templates': typeof DashboardEmailTemplatesRoute
  '/financien': typeof DashboardFinancienRoute
  '/goedkeuringen': typeof DashboardGoedkeuringenRoute
  '/jaarplan': typeof DashboardJaarplanRoute
  '/kerngegevens': typeof DashboardKerngegevensRoute
  '/leden-betalingen': typeof DashboardLedenBetalingenRoute
  '/mijn-account': typeof DashboardMijnAccountRoute
  '/a/$shareCode': typeof AShareCodeRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/enquete-extern/$id': typeof EnqueteExternIdRoute
  '/extern/profiel': typeof ExternProfielRoute
  '/': typeof DashboardIndexRoute
  '/extern': typeof ExternIndexRoute
  '/agenda/$eventId': typeof DashboardAgendaEventIdRoute
  '/externe-partijen/$id': typeof DashboardExternePartijenIdRoute
  '/leden/$id': typeof DashboardLedenIdRoute
  '/ledenvoordelen/$id': typeof DashboardLedenvoordelenIdRoute
  '/locaties/$gemeente': typeof DashboardLocatiesGemeenteRoute
  '/enquetes/$id/review': typeof EnquetesIdReviewRoute
  '/extern/gemeente/$gemeente': typeof ExternGemeenteGemeenteRoute
  '/extern/product/$id': typeof ExternProductIdRoute
  '/agenda': typeof DashboardAgendaIndexRoute
  '/coffeeshopregister': typeof DashboardCoffeeshopregisterIndexRoute
  '/enquetes': typeof DashboardEnquetesIndexRoute
  '/externe-partijen': typeof DashboardExternePartijenIndexRoute
  '/leden': typeof DashboardLedenIndexRoute
  '/ledenvoordelen': typeof DashboardLedenvoordelenIndexRoute
  '/locaties': typeof DashboardLocatiesIndexRoute
  '/coffeeshopregister/gemeente/$gemeente': typeof DashboardCoffeeshopregisterGemeenteGemeenteRoute
  '/enquetes/$id/beheer': typeof DashboardEnquetesIdBeheerRoute
  '/api/public/agenda-image/$code': typeof ApiPublicAgendaImageCodeRoute
  '/enquetes/$id': typeof DashboardEnquetesIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_dashboard': typeof DashboardRouteWithChildren
  '/extern-login': typeof ExternLoginRoute
  '/koppelen': typeof KoppelenRoute
  '/login': typeof LoginRoute
  '/mfa-setup': typeof MfaSetupRoute
  '/mfa-verify': typeof MfaVerifyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/_dashboard/accounts': typeof DashboardAccountsRoute
  '/_dashboard/bestuur-beheer': typeof DashboardBestuurBeheerRoute
  '/_dashboard/community': typeof DashboardCommunityRoute
  '/_dashboard/email-templates': typeof DashboardEmailTemplatesRoute
  '/_dashboard/financien': typeof DashboardFinancienRoute
  '/_dashboard/goedkeuringen': typeof DashboardGoedkeuringenRoute
  '/_dashboard/jaarplan': typeof DashboardJaarplanRoute
  '/_dashboard/kerngegevens': typeof DashboardKerngegevensRoute
  '/_dashboard/leden-betalingen': typeof DashboardLedenBetalingenRoute
  '/_dashboard/mijn-account': typeof DashboardMijnAccountRoute
  '/a/$shareCode': typeof AShareCodeRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/enquete-extern/$id': typeof EnqueteExternIdRoute
  '/extern/profiel': typeof ExternProfielRoute
  '/_dashboard/': typeof DashboardIndexRoute
  '/extern/': typeof ExternIndexRoute
  '/_dashboard/agenda/$eventId': typeof DashboardAgendaEventIdRoute
  '/_dashboard/externe-partijen/$id': typeof DashboardExternePartijenIdRoute
  '/_dashboard/leden/$id': typeof DashboardLedenIdRoute
  '/_dashboard/ledenvoordelen/$id': typeof DashboardLedenvoordelenIdRoute
  '/_dashboard/locaties/$gemeente': typeof DashboardLocatiesGemeenteRoute
  '/enquetes/$id/review': typeof EnquetesIdReviewRoute
  '/extern/gemeente/$gemeente': typeof ExternGemeenteGemeenteRoute
  '/extern/product/$id': typeof ExternProductIdRoute
  '/_dashboard/agenda/': typeof DashboardAgendaIndexRoute
  '/_dashboard/coffeeshopregister/': typeof DashboardCoffeeshopregisterIndexRoute
  '/_dashboard/enquetes/': typeof DashboardEnquetesIndexRoute
  '/_dashboard/externe-partijen/': typeof DashboardExternePartijenIndexRoute
  '/_dashboard/leden/': typeof DashboardLedenIndexRoute
  '/_dashboard/ledenvoordelen/': typeof DashboardLedenvoordelenIndexRoute
  '/_dashboard/locaties/': typeof DashboardLocatiesIndexRoute
  '/_dashboard/coffeeshopregister/gemeente/$gemeente': typeof DashboardCoffeeshopregisterGemeenteGemeenteRoute
  '/_dashboard/enquetes/$id/beheer': typeof DashboardEnquetesIdBeheerRoute
  '/api/public/agenda-image/$code': typeof ApiPublicAgendaImageCodeRoute
  '/_dashboard/enquetes/$id/': typeof DashboardEnquetesIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/extern-login'
    | '/koppelen'
    | '/login'
    | '/mfa-setup'
    | '/mfa-verify'
    | '/reset-password'
    | '/unsubscribe'
    | '/accounts'
    | '/bestuur-beheer'
    | '/community'
    | '/email-templates'
    | '/financien'
    | '/goedkeuringen'
    | '/jaarplan'
    | '/kerngegevens'
    | '/leden-betalingen'
    | '/mijn-account'
    | '/a/$shareCode'
    | '/checkout/return'
    | '/enquete-extern/$id'
    | '/extern/profiel'
    | '/extern/'
    | '/agenda/$eventId'
    | '/externe-partijen/$id'
    | '/leden/$id'
    | '/ledenvoordelen/$id'
    | '/locaties/$gemeente'
    | '/enquetes/$id/review'
    | '/extern/gemeente/$gemeente'
    | '/extern/product/$id'
    | '/agenda/'
    | '/coffeeshopregister/'
    | '/enquetes/'
    | '/externe-partijen/'
    | '/leden/'
    | '/ledenvoordelen/'
    | '/locaties/'
    | '/coffeeshopregister/gemeente/$gemeente'
    | '/enquetes/$id/beheer'
    | '/api/public/agenda-image/$code'
    | '/enquetes/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/extern-login'
    | '/koppelen'
    | '/login'
    | '/mfa-setup'
    | '/mfa-verify'
    | '/reset-password'
    | '/unsubscribe'
    | '/accounts'
    | '/bestuur-beheer'
    | '/community'
    | '/email-templates'
    | '/financien'
    | '/goedkeuringen'
    | '/jaarplan'
    | '/kerngegevens'
    | '/leden-betalingen'
    | '/mijn-account'
    | '/a/$shareCode'
    | '/checkout/return'
    | '/enquete-extern/$id'
    | '/extern/profiel'
    | '/'
    | '/extern'
    | '/agenda/$eventId'
    | '/externe-partijen/$id'
    | '/leden/$id'
    | '/ledenvoordelen/$id'
    | '/locaties/$gemeente'
    | '/enquetes/$id/review'
    | '/extern/gemeente/$gemeente'
    | '/extern/product/$id'
    | '/agenda'
    | '/coffeeshopregister'
    | '/enquetes'
    | '/externe-partijen'
    | '/leden'
    | '/ledenvoordelen'
    | '/locaties'
    | '/coffeeshopregister/gemeente/$gemeente'
    | '/enquetes/$id/beheer'
    | '/api/public/agenda-image/$code'
    | '/enquetes/$id'
  id:
    | '__root__'
    | '/_dashboard'
    | '/extern-login'
    | '/koppelen'
    | '/login'
    | '/mfa-setup'
    | '/mfa-verify'
    | '/reset-password'
    | '/unsubscribe'
    | '/_dashboard/accounts'
    | '/_dashboard/bestuur-beheer'
    | '/_dashboard/community'
    | '/_dashboard/email-templates'
    | '/_dashboard/financien'
    | '/_dashboard/goedkeuringen'
    | '/_dashboard/jaarplan'
    | '/_dashboard/kerngegevens'
    | '/_dashboard/leden-betalingen'
    | '/_dashboard/mijn-account'
    | '/a/$shareCode'
    | '/checkout/return'
    | '/enquete-extern/$id'
    | '/extern/profiel'
    | '/_dashboard/'
    | '/extern/'
    | '/_dashboard/agenda/$eventId'
    | '/_dashboard/externe-partijen/$id'
    | '/_dashboard/leden/$id'
    | '/_dashboard/ledenvoordelen/$id'
    | '/_dashboard/locaties/$gemeente'
    | '/enquetes/$id/review'
    | '/extern/gemeente/$gemeente'
    | '/extern/product/$id'
    | '/_dashboard/agenda/'
    | '/_dashboard/coffeeshopregister/'
    | '/_dashboard/enquetes/'
    | '/_dashboard/externe-partijen/'
    | '/_dashboard/leden/'
    | '/_dashboard/ledenvoordelen/'
    | '/_dashboard/locaties/'
    | '/_dashboard/coffeeshopregister/gemeente/$gemeente'
    | '/_dashboard/enquetes/$id/beheer'
    | '/api/public/agenda-image/$code'
    | '/_dashboard/enquetes/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DashboardRoute: typeof DashboardRouteWithChildren
  ExternLoginRoute: typeof ExternLoginRoute
  KoppelenRoute: typeof KoppelenRoute
  LoginRoute: typeof LoginRoute
  MfaSetupRoute: typeof MfaSetupRoute
  MfaVerifyRoute: typeof MfaVerifyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  UnsubscribeRoute: typeof UnsubscribeRoute
  AShareCodeRoute: typeof AShareCodeRoute
  CheckoutReturnRoute: typeof CheckoutReturnRoute
  EnqueteExternIdRoute: typeof EnqueteExternIdRoute
  ExternProfielRoute: typeof ExternProfielRoute
  ExternIndexRoute: typeof ExternIndexRoute
  EnquetesIdReviewRoute: typeof EnquetesIdReviewRoute
  ExternGemeenteGemeenteRoute: typeof ExternGemeenteGemeenteRoute
  ExternProductIdRoute: typeof ExternProductIdRoute
  ApiPublicAgendaImageCodeRoute: typeof ApiPublicAgendaImageCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/extern-login': {
      id: '/extern-login'
      path: '/extern-login'
      fullPath: '/extern-login'
      preLoaderRoute: typeof ExternLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/koppelen': {
      id: '/koppelen'
      path: '/koppelen'
      fullPath: '/koppelen'
      preLoaderRoute: typeof KoppelenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mfa-setup': {
      id: '/mfa-setup'
      path: '/mfa-setup'
      fullPath: '/mfa-setup'
      preLoaderRoute: typeof MfaSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mfa-verify': {
      id: '/mfa-verify'
      path: '/mfa-verify'
      fullPath: '/mfa-verify'
      preLoaderRoute: typeof MfaVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unsubscribe': {
      id: '/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/unsubscribe'
      preLoaderRoute: typeof UnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/': {
      id: '/_dashboard/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/accounts': {
      id: '/_dashboard/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof DashboardAccountsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/bestuur-beheer': {
      id: '/_dashboard/bestuur-beheer'
      path: '/bestuur-beheer'
      fullPath: '/bestuur-beheer'
      preLoaderRoute: typeof DashboardBestuurBeheerRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/community': {
      id: '/_dashboard/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof DashboardCommunityRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/email-templates': {
      id: '/_dashboard/email-templates'
      path: '/email-templates'
      fullPath: '/email-templates'
      preLoaderRoute: typeof DashboardEmailTemplatesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/financien': {
      id: '/_dashboard/financien'
      path: '/financien'
      fullPath: '/financien'
      preLoaderRoute: typeof DashboardFinancienRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/goedkeuringen': {
      id: '/_dashboard/goedkeuringen'
      path: '/goedkeuringen'
      fullPath: '/goedkeuringen'
      preLoaderRoute: typeof DashboardGoedkeuringenRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/jaarplan': {
      id: '/_dashboard/jaarplan'
      path: '/jaarplan'
      fullPath: '/jaarplan'
      preLoaderRoute: typeof DashboardJaarplanRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/kerngegevens': {
      id: '/_dashboard/kerngegevens'
      path: '/kerngegevens'
      fullPath: '/kerngegevens'
      preLoaderRoute: typeof DashboardKerngegevensRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/leden-betalingen': {
      id: '/_dashboard/leden-betalingen'
      path: '/leden-betalingen'
      fullPath: '/leden-betalingen'
      preLoaderRoute: typeof DashboardLedenBetalingenRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/mijn-account': {
      id: '/_dashboard/mijn-account'
      path: '/mijn-account'
      fullPath: '/mijn-account'
      preLoaderRoute: typeof DashboardMijnAccountRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/a/$shareCode': {
      id: '/a/$shareCode'
      path: '/a/$shareCode'
      fullPath: '/a/$shareCode'
      preLoaderRoute: typeof AShareCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/return': {
      id: '/checkout/return'
      path: '/checkout/return'
      fullPath: '/checkout/return'
      preLoaderRoute: typeof CheckoutReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enquete-extern/$id': {
      id: '/enquete-extern/$id'
      path: '/enquete-extern/$id'
      fullPath: '/enquete-extern/$id'
      preLoaderRoute: typeof EnqueteExternIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/extern/': {
      id: '/extern/'
      path: '/extern'
      fullPath: '/extern/'
      preLoaderRoute: typeof ExternIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/extern/profiel': {
      id: '/extern/profiel'
      path: '/extern/profiel'
      fullPath: '/extern/profiel'
      preLoaderRoute: typeof ExternProfielRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/agenda/': {
      id: '/_dashboard/agenda/'
      path: '/agenda'
      fullPath: '/agenda/'
      preLoaderRoute: typeof DashboardAgendaIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/agenda/$eventId': {
      id: '/_dashboard/agenda/$eventId'
      path: '/agenda/$eventId'
      fullPath: '/agenda/$eventId'
      preLoaderRoute: typeof DashboardAgendaEventIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/coffeeshopregister/': {
      id: '/_dashboard/coffeeshopregister/'
      path: '/coffeeshopregister'
      fullPath: '/coffeeshopregister/'
      preLoaderRoute: typeof DashboardCoffeeshopregisterIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/enquetes/': {
      id: '/_dashboard/enquetes/'
      path: '/enquetes'
      fullPath: '/enquetes/'
      preLoaderRoute: typeof DashboardEnquetesIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/externe-partijen/': {
      id: '/_dashboard/externe-partijen/'
      path: '/externe-partijen'
      fullPath: '/externe-partijen/'
      preLoaderRoute: typeof DashboardExternePartijenIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/externe-partijen/$id': {
      id: '/_dashboard/externe-partijen/$id'
      path: '/externe-partijen/$id'
      fullPath: '/externe-partijen/$id'
      preLoaderRoute: typeof DashboardExternePartijenIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/leden/': {
      id: '/_dashboard/leden/'
      path: '/leden'
      fullPath: '/leden/'
      preLoaderRoute: typeof DashboardLedenIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/leden/$id': {
      id: '/_dashboard/leden/$id'
      path: '/leden/$id'
      fullPath: '/leden/$id'
      preLoaderRoute: typeof DashboardLedenIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/ledenvoordelen/': {
      id: '/_dashboard/ledenvoordelen/'
      path: '/ledenvoordelen'
      fullPath: '/ledenvoordelen/'
      preLoaderRoute: typeof DashboardLedenvoordelenIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/ledenvoordelen/$id': {
      id: '/_dashboard/ledenvoordelen/$id'
      path: '/ledenvoordelen/$id'
      fullPath: '/ledenvoordelen/$id'
      preLoaderRoute: typeof DashboardLedenvoordelenIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/locaties/': {
      id: '/_dashboard/locaties/'
      path: '/locaties'
      fullPath: '/locaties/'
      preLoaderRoute: typeof DashboardLocatiesIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/locaties/$gemeente': {
      id: '/_dashboard/locaties/$gemeente'
      path: '/locaties/$gemeente'
      fullPath: '/locaties/$gemeente'
      preLoaderRoute: typeof DashboardLocatiesGemeenteRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/enquetes/$id/review': {
      id: '/enquetes/$id/review'
      path: '/enquetes/$id/review'
      fullPath: '/enquetes/$id/review'
      preLoaderRoute: typeof EnquetesIdReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/extern/gemeente/$gemeente': {
      id: '/extern/gemeente/$gemeente'
      path: '/extern/gemeente/$gemeente'
      fullPath: '/extern/gemeente/$gemeente'
      preLoaderRoute: typeof ExternGemeenteGemeenteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/extern/product/$id': {
      id: '/extern/product/$id'
      path: '/extern/product/$id'
      fullPath: '/extern/product/$id'
      preLoaderRoute: typeof ExternProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/coffeeshopregister/gemeente/$gemeente': {
      id: '/_dashboard/coffeeshopregister/gemeente/$gemeente'
      path: '/coffeeshopregister/gemeente/$gemeente'
      fullPath: '/coffeeshopregister/gemeente/$gemeente'
      preLoaderRoute: typeof DashboardCoffeeshopregisterGemeenteGemeenteRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/enquetes/$id/': {
      id: '/_dashboard/enquetes/$id/'
      path: '/enquetes/$id'
      fullPath: '/enquetes/$id/'
      preLoaderRoute: typeof DashboardEnquetesIdIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/enquetes/$id/beheer': {
      id: '/_dashboard/enquetes/$id/beheer'
      path: '/enquetes/$id/beheer'
      fullPath: '/enquetes/$id/beheer'
      preLoaderRoute: typeof DashboardEnquetesIdBeheerRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/api/public/agenda-image/$code': {
      id: '/api/public/agenda-image/$code'
      path: '/api/public/agenda-image/$code'
      fullPath: '/api/public/agenda-image/$code'
      preLoaderRoute: typeof ApiPublicAgendaImageCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardRouteChildren {
  DashboardAccountsRoute: typeof DashboardAccountsRoute
  DashboardBestuurBeheerRoute: typeof DashboardBestuurBeheerRoute
  DashboardCommunityRoute: typeof DashboardCommunityRoute
  DashboardEmailTemplatesRoute: typeof DashboardEmailTemplatesRoute
  DashboardFinancienRoute: typeof DashboardFinancienRoute
  DashboardGoedkeuringenRoute: typeof DashboardGoedkeuringenRoute
  DashboardJaarplanRoute: typeof DashboardJaarplanRoute
  DashboardKerngegevensRoute: typeof DashboardKerngegevensRoute
  DashboardLedenBetalingenRoute: typeof DashboardLedenBetalingenRoute
  DashboardMijnAccountRoute: typeof DashboardMijnAccountRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardAgendaEventIdRoute: typeof DashboardAgendaEventIdRoute
  DashboardExternePartijenIdRoute: typeof DashboardExternePartijenIdRoute
  DashboardLedenIdRoute: typeof DashboardLedenIdRoute
  DashboardLedenvoordelenIdRoute: typeof DashboardLedenvoordelenIdRoute
  DashboardLocatiesGemeenteRoute: typeof DashboardLocatiesGemeenteRoute
  DashboardAgendaIndexRoute: typeof DashboardAgendaIndexRoute
  DashboardCoffeeshopregisterIndexRoute: typeof DashboardCoffeeshopregisterIndexRoute
  DashboardEnquetesIndexRoute: typeof DashboardEnquetesIndexRoute
  DashboardExternePartijenIndexRoute: typeof DashboardExternePartijenIndexRoute
  DashboardLedenIndexRoute: typeof DashboardLedenIndexRoute
  DashboardLedenvoordelenIndexRoute: typeof DashboardLedenvoordelenIndexRoute
  DashboardLocatiesIndexRoute: typeof DashboardLocatiesIndexRoute
  DashboardCoffeeshopregisterGemeenteGemeenteRoute: typeof DashboardCoffeeshopregisterGemeenteGemeenteRoute
  DashboardEnquetesIdBeheerRoute: typeof DashboardEnquetesIdBeheerRoute
  DashboardEnquetesIdIndexRoute: typeof DashboardEnquetesIdIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAccountsRoute: DashboardAccountsRoute,
  DashboardBestuurBeheerRoute: DashboardBestuurBeheerRoute,
  DashboardCommunityRoute: DashboardCommunityRoute,
  DashboardEmailTemplatesRoute: DashboardEmailTemplatesRoute,
  DashboardFinancienRoute: DashboardFinancienRoute,
  DashboardGoedkeuringenRoute: DashboardGoedkeuringenRoute,
  DashboardJaarplanRoute: DashboardJaarplanRoute,
  DashboardKerngegevensRoute: DashboardKerngegevensRoute,
  DashboardLedenBetalingenRoute: DashboardLedenBetalingenRoute,
  DashboardMijnAccountRoute: DashboardMijnAccountRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardAgendaEventIdRoute: DashboardAgendaEventIdRoute,
  DashboardExternePartijenIdRoute: DashboardExternePartijenIdRoute,
  DashboardLedenIdRoute: DashboardLedenIdRoute,
  DashboardLedenvoordelenIdRoute: DashboardLedenvoordelenIdRoute,
  DashboardLocatiesGemeenteRoute: DashboardLocatiesGemeenteRoute,
  DashboardAgendaIndexRoute: DashboardAgendaIndexRoute,
  DashboardCoffeeshopregisterIndexRoute: DashboardCoffeeshopregisterIndexRoute,
  DashboardEnquetesIndexRoute: DashboardEnquetesIndexRoute,
  DashboardExternePartijenIndexRoute: DashboardExternePartijenIndexRoute,
  DashboardLedenIndexRoute: DashboardLedenIndexRoute,
  DashboardLedenvoordelenIndexRoute: DashboardLedenvoordelenIndexRoute,
  DashboardLocatiesIndexRoute: DashboardLocatiesIndexRoute,
  DashboardCoffeeshopregisterGemeenteGemeenteRoute:
    DashboardCoffeeshopregisterGemeenteGemeenteRoute,
  DashboardEnquetesIdBeheerRoute: DashboardEnquetesIdBeheerRoute,
  DashboardEnquetesIdIndexRoute: DashboardEnquetesIdIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  DashboardRoute: DashboardRouteWithChildren,
  ExternLoginRoute: ExternLoginRoute,
  KoppelenRoute: KoppelenRoute,
  LoginRoute: LoginRoute,
  MfaSetupRoute: MfaSetupRoute,
  MfaVerifyRoute: MfaVerifyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  UnsubscribeRoute: UnsubscribeRoute,
  AShareCodeRoute: AShareCodeRoute,
  CheckoutReturnRoute: CheckoutReturnRoute,
  EnqueteExternIdRoute: EnqueteExternIdRoute,
  ExternProfielRoute: ExternProfielRoute,
  ExternIndexRoute: ExternIndexRoute,
  EnquetesIdReviewRoute: EnquetesIdReviewRoute,
  ExternGemeenteGemeenteRoute: ExternGemeenteGemeenteRoute,
  ExternProductIdRoute: ExternProductIdRoute,
  ApiPublicAgendaImageCodeRoute: ApiPublicAgendaImageCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
