
DELETE FROM survey_questions WHERE survey_id = 'a1b2c3d4-e5f6-7890-abcd-ef1234567890';

INSERT INTO survey_questions (survey_id, question_text, question_type, options, required, sort_order) VALUES
('a1b2c3d4-e5f6-7890-abcd-ef1234567890', 'Welke pin-/betaaldienstverlener gebruikt u momenteel?', 'checkbox', '["Rabobank","CCV","Worldline","EMS / Fiserv","Adyen","SumUp","YourSafe","CM.com","Mollie","Anders, namelijk: …"]'::jsonb, true, 0),
('a1b2c3d4-e5f6-7890-abcd-ef1234567890', 'Zit u momenteel bij deze aanbieder omdat dit uw voorkeur heeft, of omdat dit de enige werkbare optie is?', 'radio', '["Mijn voorkeur","Enige werkbare optie","Weet ik niet"]'::jsonb, true, 1),
('a1b2c3d4-e5f6-7890-abcd-ef1234567890', 'Heeft u overwogen om over te stappen naar een andere aanbieder?', 'radio', '["Ja","Nee"]'::jsonb, true, 2),
('a1b2c3d4-e5f6-7890-abcd-ef1234567890', 'Zo ja, waarom heeft u uiteindelijk de overstap niet gemaakt? (meerdere antwoorden mogelijk)', 'checkbox', '["Ik vertrouw de aanbieder niet","Ik twijfel aan de continuïteit / stabiliteit van de aanbieder","Ik ben bang dat de dienstverlening later alsnog wordt beëindigd","De kosten / tarieven zijn te hoog","Mijn kassasysteem of kassa-aanbieder ondersteunt deze aanbieder niet","De contractvoorwaarden zijn onduidelijk of ongunstig","De uitbetalingstermijnen zijn ongunstig","De aanbieder is te klein of te onbekend","Ik heb slechte ervaringen gehoord uit de sector","Ik verwacht problemen met compliance / acceptatie achteraf","Ik ben geweigerd","Mijn sector werd niet geaccepteerd","Ik kreeg geen contract","Te veel risico om zonder pin te zitten tijdens overstap","Geen betrouwbare alternatieven","Anders, namelijk: …"]'::jsonb, false, 3),
('a1b2c3d4-e5f6-7890-abcd-ef1234567890', 'Bij welke aanbieders heeft u geprobeerd pin-diensten af te nemen, maar bent u geweigerd? (meerdere antwoorden mogelijk)', 'checkbox', '["Rabobank","CCV","Worldline","EMS / Fiserv","Adyen","SumUp","YourSafe","CM.com","Mollie","Anders, namelijk: …","Niet van toepassing"]'::jsonb, true, 4),
('a1b2c3d4-e5f6-7890-abcd-ef1234567890', 'Heeft u het gevoel dat u wordt geweigerd vanwege uw sector (coffeeshop)?', 'radio', '["Ja","Nee","Weet ik niet"]'::jsonb, true, 5),
('a1b2c3d4-e5f6-7890-abcd-ef1234567890', 'Vindt u dat er voor coffeeshops een goed functionerende markt voor pinverwerking bestaat?', 'radio', '["Ja","Nee","Weet ik niet"]'::jsonb, true, 6),
('a1b2c3d4-e5f6-7890-abcd-ef1234567890', 'Als u volledig vrij kon kiezen, bij welke pin-/betaaldienstverlener zou u het liefst terechtkunnen?', 'checkbox', '["Rabobank","CCV","Worldline","EMS / Fiserv","Adyen","SumUp","YourSafe","CM.com","Mollie","Anders, namelijk: …","Weet ik niet"]'::jsonb, true, 7),
('a1b2c3d4-e5f6-7890-abcd-ef1234567890', 'Waarom heeft deze aanbieder uw voorkeur? (meerdere antwoorden mogelijk)', 'checkbox', '["Ik vertrouw deze aanbieder meer","Deze aanbieder is stabieler","Minder risico op beëindiging","Betere tarieven / lagere kosten","Betere service / bereikbaarheid","Betere koppeling met kassasysteem","Deze aanbieder accepteert coffeeshops daadwerkelijk","Anders, namelijk: …"]'::jsonb, true, 8),
('a1b2c3d4-e5f6-7890-abcd-ef1234567890', 'Wat zijn voor u de belangrijkste bezwaren tegen aanbieders die aangeven coffeeshops wél te willen onboarden? (maximaal 3 antwoorden)', 'checkbox', '["Ik vertrouw deze aanbieder niet","Ik twijfel aan de continuïteit / stabiliteit van deze aanbieder","Ik ben bang dat de dienstverlening later alsnog wordt beëindigd","De kosten / tarieven zijn te hoog","Mijn kassasysteem of kassa-aanbieder ondersteunt deze aanbieder niet","De contractvoorwaarden zijn onduidelijk of ongunstig","De uitbetalingstermijnen zijn ongunstig","De aanbieder is te klein of te onbekend","Ik heb slechte ervaringen gehoord uit de sector","Ik verwacht problemen met compliance / acceptatie achteraf","Anders, namelijk: …"]'::jsonb, true, 9),
('a1b2c3d4-e5f6-7890-abcd-ef1234567890', 'Over welke aanbieder(s) gaan deze bezwaren vooral? (meerdere antwoorden mogelijk)', 'checkbox', '["YourSafe","CM.com","Mollie","EMS / Fiserv","SumUp","Adyen","Anders, namelijk: …"]'::jsonb, true, 10);
