
-- Delete old questions for this survey
DELETE FROM survey_questions WHERE survey_id = 'a1b2c3d4-e5f6-7890-abcd-ef1234567890';

-- Insert updated 19 questions
INSERT INTO survey_questions (survey_id, question_text, question_type, options, required, sort_order) VALUES
('a1b2c3d4-e5f6-7890-abcd-ef1234567890', 'Welke pin-/betaaldienstverlener gebruikt u momenteel?', 'radio', '["Rabobank","CCV","Worldline","EMS / Fiserv","Adyen","SumUp","Anders, namelijk: …"]', true, 0),
('a1b2c3d4-e5f6-7890-abcd-ef1234567890', 'Zit u momenteel bij deze aanbieder omdat dit uw voorkeur heeft, of omdat dit de enige werkbare optie is?', 'radio', '["Mijn voorkeur","Enige werkbare optie","Weet ik niet"]', true, 1),
('a1b2c3d4-e5f6-7890-abcd-ef1234567890', 'Heeft u overwogen om over te stappen naar een andere aanbieder?', 'radio', '["Ja","Nee"]', true, 2),
('a1b2c3d4-e5f6-7890-abcd-ef1234567890', 'Zo ja, waarom heeft u uiteindelijk niet de overstap gemaakt? (meerdere antwoorden mogelijk)', 'checkbox', '["Ik ben geweigerd","Mijn sector werd niet geaccepteerd","Ik kreeg geen contract","Te veel risico om zonder pin te zitten","Geen betrouwbare alternatieven","Technische of praktische problemen bij overstappen","Kosten waren te hoog","Anders, namelijk: …"]', false, 3),
('a1b2c3d4-e5f6-7890-abcd-ef1234567890', 'Acht u het realistisch om op korte termijn over te stappen naar een andere aanbieder?', 'radio', '["Ja","Nee","Weet ik niet"]', true, 4),
('a1b2c3d4-e5f6-7890-abcd-ef1234567890', 'Wat zijn voor u de belangrijkste bezwaren tegen overstappen? (maximaal 3 antwoorden)', 'checkbox', '["Ik vertrouw de aanbieder(s) niet","Risico dat dienstverlening wordt stopgezet","Kosten / tarieven te hoog","Mijn kassasysteem of kassa-aanbieder ondersteunt deze aanbieder niet","Onzekerheid over contractvoorwaarden","Te veel operationeel risico","Geen stabiele aanbieders in de markt","Anders, namelijk: …"]', true, 5),
('a1b2c3d4-e5f6-7890-abcd-ef1234567890', 'Hoe groot acht u het risico dat uw huidige aanbieder de dienstverlening stopzet?', 'radio', '["Zeer groot","Groot","Beperkt","Geen"]', true, 6),
('a1b2c3d4-e5f6-7890-abcd-ef1234567890', 'Bij welke aanbieders heeft u geprobeerd pin-diensten af te nemen, maar bent u geweigerd? (meerdere antwoorden mogelijk)', 'checkbox', '["Rabobank","CCV","Worldline","EMS / Fiserv","Adyen","SumUp","YourSafe","CM.com","Mollie","Anders, namelijk: …","Niet van toepassing"]', true, 7),
('a1b2c3d4-e5f6-7890-abcd-ef1234567890', 'Heeft u het gevoel dat u wordt geweigerd vanwege uw sector (coffeeshop)?', 'radio', '["Ja","Nee","Weet ik niet"]', true, 8),
('a1b2c3d4-e5f6-7890-abcd-ef1234567890', 'Hoe afhankelijk is uw onderneming van pinbetalingen?', 'radio', '["Minder dan 25% van de omzet","25–50%","50–75%","Meer dan 75%"]', true, 9),
('a1b2c3d4-e5f6-7890-abcd-ef1234567890', 'Hoe lang denkt u nodig te hebben om een nieuwe pinverwerker te regelen als uw huidige stopt?', 'radio', '["Minder dan 1 week","1–4 weken","Meer dan 1 maand","Onzeker / mogelijk niet haalbaar"]', true, 10),
('a1b2c3d4-e5f6-7890-abcd-ef1234567890', 'Heeft u ooit zonder werkende pinvoorziening gezeten door problemen met uw aanbieder?', 'radio', '["Ja","Nee"]', true, 11),
('a1b2c3d4-e5f6-7890-abcd-ef1234567890', 'Zo ja, wat was hiervan de impact op uw onderneming? (meerdere antwoorden mogelijk)', 'checkbox', '["Tijdelijk omzetverlies","Structureel omzetverlies","Problemen in de dagelijkse bedrijfsvoering","Problemen met klanten","Extra veiligheidsrisico''s door meer contant geld","Problemen met de bank (bijv. door toename contant geld)","Anders, namelijk: …"]', false, 12),
('a1b2c3d4-e5f6-7890-abcd-ef1234567890', 'Heeft u ervaring met een pinverwerker die later alsnog de dienstverlening heeft beëindigd?', 'radio', '["Ja","Nee"]', true, 13),
('a1b2c3d4-e5f6-7890-abcd-ef1234567890', 'Vindt u dat er voor coffeeshops een goed functionerende markt voor pinverwerking bestaat?', 'radio', '["Ja","Nee","Weet ik niet"]', true, 14),
('a1b2c3d4-e5f6-7890-abcd-ef1234567890', 'Als u volledig vrij kon kiezen, bij welke pin-/betaaldienstverlener zou u het liefst terechtkunnen?', 'radio', '["Rabobank","CCV","Worldline","EMS / Fiserv","Adyen","SumUp","YourSafe","CM.com","Mollie","Anders, namelijk: …","Weet ik niet"]', true, 15),
('a1b2c3d4-e5f6-7890-abcd-ef1234567890', 'Waarom heeft deze aanbieder uw voorkeur? (meerdere antwoorden mogelijk)', 'checkbox', '["Ik vertrouw deze aanbieder meer","Deze aanbieder is stabieler","Minder risico op beëindiging","Betere tarieven / lagere kosten","Betere service / bereikbaarheid","Betere koppeling met kassasysteem","Deze aanbieder accepteert coffeeshops daadwerkelijk","Anders, namelijk: …"]', true, 16),
('a1b2c3d4-e5f6-7890-abcd-ef1234567890', 'Wat zijn voor u de belangrijkste bezwaren tegen aanbieders die aangeven coffeeshops wél te willen onboarden? (maximaal 3 antwoorden)', 'checkbox', '["Ik vertrouw deze aanbieder niet","Ik twijfel aan de continuïteit / stabiliteit van deze aanbieder","Ik ben bang dat de dienstverlening later alsnog wordt beëindigd","De kosten / tarieven zijn te hoog","Mijn kassasysteem of kassa-aanbieder ondersteunt deze aanbieder niet","De contractvoorwaarden zijn onduidelijk of ongunstig","De uitbetalingstermijnen zijn ongunstig","De aanbieder is te klein of te onbekend","Ik heb slechte ervaringen gehoord uit de sector","Ik verwacht problemen met compliance / acceptatie achteraf","Anders, namelijk: …"]', true, 17),
('a1b2c3d4-e5f6-7890-abcd-ef1234567890', 'Over welke aanbieder(s) gaan deze bezwaren vooral? (meerdere antwoorden mogelijk)', 'checkbox', '["YourSafe","CM.com","Mollie","EMS / Fiserv","SumUp","Adyen","Anders, namelijk: …"]', true, 18);
